name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          start: "npm run dev"
          build: "npm run build"
      
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
            cypress/results
          if-no-files-found: ignore

          
